#!/usr/bin/env python3
"""Registry of Thai SFT sources, with the licence filter each one needs.

The licence recorded on a HuggingFace repo is what the uploader typed. What matters is what
the data permits, which for generated data is inherited from the model that produced it and
for aggregated data varies row by row. Every entry here therefore carries a `row_filter`, and
a source with no filter is one that has been checked and genuinely needs none.

Measured 2026-08-23 from the datasets-server statistics endpoint:

  WangchanThaiInstruct   40,000 rows, of which 34,986 are cc-by-nc-4.0.
                         Only 5,014 are cc-by-sa-4.0, and the same 5,014 appear in both the
                         default and paper configs, so the usable count is 5,014, not 10,028.
                         86.6% of the flagship human-written Thai instruction set cannot go
                         into a model anyone intends to release for commercial use.
  seed-free 120k         118,898 rows. Tagged MIT, generated by Qwen2-72B-Instruct, whose
                         Tongyi Qianwen licence forbids improving "any other large language
                         model (excluding Tongyi Qianwen or derivative works thereof)".
                         Usable here only because the base model is Qwen3. See
                         SFT_DATA_LICENSE_AUDIT.md - this reading needs confirmation.
  Aya (Thai)             724 rows out of 202,362. Human-written, Apache-2.0.
  thai-local-instruction 39,829 rows, cc-by-4.0.
  OASST2 (Thai subset)   extracted from 128,575 multilingual rows.
"""
from __future__ import annotations

# Licences that permit training a model intended for open release. Anything outside this set
# is dropped with a count rather than silently included.
ALLOWED = {"cc-by-sa-4.0", "cc-by-4.0", "apache-2.0", "mit", "cc0-1.0"}
DENIED_SUBSTRINGS = ("nc", "noncommercial", "non-commercial")


def licence_allowed(value: str | None) -> bool:
    if not value:
        return False                      # absent licence grants nothing
    v = str(value).strip().lower()
    if any(s in v.split("-") or s in v for s in DENIED_SUBSTRINGS):
        return False
    return v in ALLOWED


SOURCES = [
    {
        "name": "wangchan_thai_instruct",
        "repo": "airesearch/WangchanThaiInstruct",
        "config": "default",
        "splits": ["train", "test"],
        "provenance": "human-written",
        "licence_note": "per-row; 86.6% cc-by-nc-4.0 and therefore excluded",
        "row_licence_field": "License",
        "map": lambda r: (r.get("Instruction"), r.get("Input"), r.get("Output")),
    },
    {
        "name": "seed_free_120k",
        "repo": "airesearch/wangchanx-seed-free-synthetic-instruct-thai-120k",
        "config": "default",
        "splits": ["train"],
        "provenance": "generated by Qwen2-72B-Instruct",
        "licence_note": "MIT tag over Tongyi Qianwen terms; usable only for a Qwen derivative",
        "row_licence_field": None,
        "fixed_licence": "mit",
        # rating is the dataset's own quality score. Synthetic answers do contradict their
        # context: one sampled row states a building has nine floors where the context says
        # four. Low-rated rows are dropped rather than trusted.
        "min_rating": 6.0,
        "map": lambda r: (r.get("instruction"), r.get("context"), r.get("output")),
    },
    {
        "name": "aya_thai",
        "repo": "CohereLabs/aya_dataset",
        "config": "default",
        "splits": ["train"],
        "provenance": "human-written",
        "licence_note": "apache-2.0, no inherited terms",
        "row_licence_field": None,
        "fixed_licence": "apache-2.0",
        "row_keep": lambda r: r.get("language_code") == "tha",
        "map": lambda r: (r.get("inputs"), None, r.get("targets")),
    },
    {
        "name": "thai_local_instruction_v2",
        "repo": "pythainlp/thai-local-instruction-v2",
        "config": "default",
        "splits": ["train"],
        "provenance": "curated from Thai local-knowledge sources",
        "licence_note": "cc-by-4.0",
        "row_licence_field": None,
        "fixed_licence": "cc-by-4.0",
        "map": lambda r: (r.get("inputs"), None, r.get("targets")),
    },
]
